### ISSUE TITLE
Slow scrolling due to constant repaints

### ISSUE THREAD

**Issue by ivancuric** [webpack/webpack.js.org#1200]
On pages such as https://webpack.js.org/guides/migrating/, the scrolling is very slow, because `.sidebar` and `.gitter__button` keep repainting.

A quick fix is adding `will-change: transform` on them to promote them to their own layers, eg:

```css
.gitter__button,
.sidebar {
	will-change: transform;
}
```
