### ISSUE TITLE
Give paragraphs a max-width

### ISSUE THREAD

**Issue by alexanderwallin** [webpack/webpack.js.org#191]
Great to see new docs in the makings!

One thing I think the old and new docs alike are suffering from is readability, the biggest problem being the number of characters per line (120+ on my 13" MacBook).

Attaching an example of paragraph width constraits and use of system font.

**Before**

<img width="956" alt="webpack1" src="https://cloud.githubusercontent.com/assets/6952455/18833352/1d7da8a4-83e8-11e6-8e57-5c5b32ae841a.png">

**After**

```css
p {
  max-width: 35em;
  line-height: 1.5;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

<img width="958" alt="webpack2" src="https://cloud.githubusercontent.com/assets/6952455/18833351/1cce74a6-83e8-11e6-8826-62b5c02ebc66.png">
