### ISSUE TITLE
Asset Management Guide Bug

### ISSUE THREAD

**Issue by amcmillion3** [webpack/webpack.js.org#5315]
I am learning webpack right now. I have been working through the guides in the official docs. I worked through the getting started guide and am halfway through the asset management guide. I am having trouble loading fonts using the guides directions. I have done the whole tutorial 3 times not following the guide to the letter and being extremely careful about everything. All three times I have gotten stuck at the loading the fonts section. I am working through The Odin Project and consulted a bunch of people there and no one has been able to get the fonts to work. I believe there may be an issue with the guide. Specifically the loading fonts part of the asset management section.

**Comment by chenxsan** [comment]
Could you push your code to github so we can check what's going on?

**Comment by glennsimon** [comment]
I see this is an old bug, but I was having the same problem with a truetype font.  The problem was in my style.css file, where I specified the url and the format of the font.  For the format, I used format('ttf'), but that is not correct.  I should have used format('truetype').  Once I made that change and rebuilt, it worked .  Here is the code:
```css
@font-face {
  font-family: 'Roboto Bold';
  src: url('./Roboto-Bold.ttf') format('truetype');
  font-weight: 600;
  font-style: normal;
}
```
