### ISSUE TITLE
Use composite action for webpack persistent caching

### ISSUE THREAD

**Issue by jongwooo** [webpack/webpack.js.org#7076]
**Description**:

Duplicate workflow steps can be abstracted into [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).

```yaml
- name: Enable webpack persistent caching
  uses: ./.github/actions/webpack-persistent-cache
```

**Why**:

For each workflow, the webpack persistent caching step is written in the same code:

```yaml
- name: Enable webpack persistent caching
  uses: actions/cache@v3
  id: build-webpack-persistent-cache
  with:
    path: node_modules/.cache
    key: build-${{ hashFiles('**/webpack.*.mjs') }}-${{ hashFiles('**/yarn.lock') }}
    restore-keys: |-
      build-${{ hashFiles('**/webpack.*.mjs') }}-${{ hashFiles('**/yarn.lock') }}
      build-${{ hashFiles('**/webpack.*.mjs') }}-
```

If requirements change, we'll need to edit it for each workflow. This makes maintenance difficult and can lead to mistakes.
